# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e10058ca0b9e38e39a59b7a4ac31628ceb0cf8d7866b2716ca7783d3f4aa89700249cb678fe3f87bdbd05b07c3bc9d748562dc322826a0806257eaf0419d9aa

test:
  secret_key_base: 9b1012fa1cfa0800531b5d1ea8f71073d4d3538c06d2de2687b80ead9c7b1917e0b06ae6a7b876b8fbab0dba037ef6f2dde9b3528ead944fb876ed5e4a0b4728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
